### ISSUE TITLE
`get tree` fails if used in a repository with no commits

### ISSUE THREAD

**Issue by asperan** [asperan/get#11]
Error message:
```
lib/get/subcommand/tree/tree.rb:86:in `transform_log': undefined method `[]' for nil:NilClass (NoMethodError)

    first_line_time = split_lines.first[1]
                                       ^^^
	from lib/get/subcommand/tree/tree.rb:70:in `view_tree'
	from lib/get/subcommand/tree/tree.rb:65:in `block in initialize'
	from lib/get.rb:64:in `main'
	from bin/get:8:in `<top (required)>'
	from bin/get:25:in `load'
	from bin/get:25:in `<main>'
```

**Comment by asperan** [comment]
Fixed in version 0.7.2
