### ISSUE TITLE
`get describe --prerelase` error if run before creating a version

### ISSUE THREAD

**Issue by asperan** [asperan/get#15]
Stacktrace:
```
git_toolbox-0.8.0/lib/get/subcommand/describe/describe.rb:100:in `prepare_prerelease_tag': undefined method `[]' for nil:NilClass (NoMethodError)

    no_changes_from_last_release = base_version_match_data[1] == new_stable_version && base_version_match_data[5].nil?
                                                          ^^^
	from git_toolbox-0.8.0/lib/get/subcommand/describe/describe.rb:87:in `next_release'
	from git_toolbox-0.8.0/lib/get/subcommand/describe/describe.rb:78:in `describe_current_commit'
	from git_toolbox-0.8.0/lib/get/subcommand/describe/describe.rb:216:in `block in setup_action'
	from git_toolbox-0.8.0/lib/get.rb:82:in `block in setup_action'
	from git_toolbox-0.8.0/lib/get.rb:54:in `main'
	from git_toolbox-0.8.0/bin/get:8:in `<top (required)>'
	from bin/get:25:in `load'
	from get:25:in `<main>'
```

**Comment by asperan** [comment]
Fixed in development. The fix will be released in a future version.
