### ISSUE TITLE
`get tree` error on unshallowed repository

### ISSUE THREAD

**Issue by asperan** [asperan/get#16]
Stack trace:
```
git_toolbox-0.8.0/lib/get/subcommand/tree/tree.rb:75:in `block in transform_log': undefined method `length' for nil:
NilClass (NoMethodError)

    split_lines.each { |element| time_padding = [time_padding, element[1].length - time_color_length].max }
                                                                         ^^^^^^^
        from git_toolbox-0.8.0/lib/get/subcommand/tree/tree.rb:75:in `each'
        from git_toolbox-0.8.0/lib/get/subcommand/tree/tree.rb:75:in `transform_log'
        from git_toolbox-0.8.0/lib/get/subcommand/tree/tree.rb:41:in `view_tree'
        from git_toolbox-0.8.0/lib/get/subcommand/tree/tree.rb:120:in `block in setup_action'
        from git_toolbox-0.8.0/lib/get.rb:82:in `block in setup_action'
        from git_toolbox-0.8.0/lib/get.rb:54:in `main'
        from git_toolbox-0.8.0/bin/get:8:in `<top (required)>'
        from bin/get:25:in `load'
        from bin/get:25:in `<main>'

```

**Comment by asperan** [comment]
The problem was happening because there can be a branch-cross in the git log:
```
| |/    
|/|     
```

In this case, there was no time reference and `element[1]` was indeed nil.

A future release will fix it.
